-- Video quality variants generated by background FFmpeg transcoding.
-- status: 'pending' (queued/running), 'ready' (streamable), 'failed' (transcode error).
-- Rows are cascade-deleted when the parent files row is removed.

CREATE TABLE video_variants (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    file_id          UUID        NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    quality          TEXT        NOT NULL,
    minio_object_key TEXT        NOT NULL UNIQUE,
    size_bytes       BIGINT      NOT NULL DEFAULT 0,
    status           TEXT        NOT NULL DEFAULT 'pending',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (file_id, quality)
);

CREATE INDEX video_variants_file_id_idx ON video_variants (file_id);
