package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"

	"apollo-sfs.com/api/models"
)

const apiKeyColumns = `id, username, name, key_prefix, key_hash,
	created_at, last_used_at, expires_at, revoked_at`

// CreateAPIKeyInput holds the parameters required to persist a new key
// alongside its scopes in a single transaction. The hash is computed and the
// raw key is generated by services/api_key.go Issue() — this method just
// writes the rows.
type CreateAPIKeyInput struct {
	Username  string
	Name      string
	KeyPrefix string
	KeyHash   string
	Scopes    []models.APIKeyScope
	ExpiresAt *time.Time
}

// CreateAPIKey inserts an api_keys row and the matching api_key_scopes rows
// inside the current transaction (caller must already be inside a ForUser tx
// so RLS is enforced).
func (q *Queries) CreateAPIKey(ctx context.Context, in CreateAPIKeyInput) (*models.APIKey, error) {
	if len(in.Scopes) == 0 {
		return nil, errors.New("CreateAPIKey: at least one scope is required")
	}
	var key models.APIKey
	var lastUsed, expires, revoked sql.NullTime
	err := q.db.QueryRowContext(ctx, `
		INSERT INTO api_keys (username, name, key_prefix, key_hash, expires_at)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING `+apiKeyColumns,
		in.Username, in.Name, in.KeyPrefix, in.KeyHash, in.ExpiresAt,
	).Scan(
		&key.ID, &key.Username, &key.Name, &key.KeyPrefix, &key.KeyHash,
		&key.CreatedAt, &lastUsed, &expires, &revoked,
	)
	if err != nil {
		return nil, fmt.Errorf("CreateAPIKey insert: %w", err)
	}
	if lastUsed.Valid {
		key.LastUsedAt = &lastUsed.Time
	}
	if expires.Valid {
		key.ExpiresAt = &expires.Time
	}
	if revoked.Valid {
		key.RevokedAt = &revoked.Time
	}

	for i := range in.Scopes {
		s := in.Scopes[i]
		var scope models.APIKeyScope
		err := q.db.QueryRowContext(ctx, `
			INSERT INTO api_key_scopes (api_key_id, operation, path_prefix)
			VALUES ($1, $2, $3)
			RETURNING id, api_key_id, operation, path_prefix
		`, key.ID, s.Operation, s.PathPrefix,
		).Scan(&scope.ID, &scope.APIKeyID, &scope.Operation, &scope.PathPrefix)
		if err != nil {
			return nil, fmt.Errorf("CreateAPIKey insert scope: %w", err)
		}
		key.Scopes = append(key.Scopes, scope)
	}
	return &key, nil
}

// ListAPIKeys returns all of the current user's API keys with their scopes
// populated. Hides revoked keys older than 90 days.
func (q *Queries) ListAPIKeys(ctx context.Context) ([]models.APIKey, error) {
	rows, err := q.db.QueryContext(ctx, `
		SELECT `+apiKeyColumns+`
		FROM api_keys
		WHERE revoked_at IS NULL OR revoked_at > NOW() - INTERVAL '90 days'
		ORDER BY created_at DESC
	`)
	if err != nil {
		return nil, fmt.Errorf("ListAPIKeys: %w", err)
	}
	defer rows.Close()
	var out []models.APIKey
	for rows.Next() {
		var k models.APIKey
		var lastUsed, expires, revoked sql.NullTime
		if err := rows.Scan(
			&k.ID, &k.Username, &k.Name, &k.KeyPrefix, &k.KeyHash,
			&k.CreatedAt, &lastUsed, &expires, &revoked,
		); err != nil {
			return nil, fmt.Errorf("ListAPIKeys scan: %w", err)
		}
		if lastUsed.Valid {
			k.LastUsedAt = &lastUsed.Time
		}
		if expires.Valid {
			k.ExpiresAt = &expires.Time
		}
		if revoked.Valid {
			k.RevokedAt = &revoked.Time
		}
		out = append(out, k)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListAPIKeys: %w", err)
	}
	// Bulk-load scopes for all returned keys.
	if len(out) == 0 {
		return out, nil
	}
	ids := make([]uuid.UUID, len(out))
	idx := make(map[uuid.UUID]int, len(out))
	for i, k := range out {
		ids[i] = k.ID
		idx[k.ID] = i
	}
	idStrings := make([]string, len(ids))
	for i, id := range ids {
		idStrings[i] = id.String()
	}
	scopeRows, err := q.db.QueryContext(ctx, `
		SELECT id, api_key_id, operation, path_prefix
		FROM api_key_scopes
		WHERE api_key_id = ANY($1)
	`, pq.Array(idStrings))
	if err != nil {
		return nil, fmt.Errorf("ListAPIKeys scopes: %w", err)
	}
	defer scopeRows.Close()
	for scopeRows.Next() {
		var s models.APIKeyScope
		if err := scopeRows.Scan(&s.ID, &s.APIKeyID, &s.Operation, &s.PathPrefix); err != nil {
			return nil, fmt.Errorf("ListAPIKeys scope scan: %w", err)
		}
		if i, ok := idx[s.APIKeyID]; ok {
			out[i].Scopes = append(out[i].Scopes, s)
		}
	}
	return out, nil
}

// GetAPIKeyByPrefix loads a key by its public prefix (the bit shown to the
// user in the UI and used at verify time). Does NOT enforce RLS — used by the
// API-key middleware which has not yet identified the user.
// Returns sql.ErrNoRows when the prefix does not match an active key.
func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (*models.APIKey, error) {
	var k models.APIKey
	var lastUsed, expires, revoked sql.NullTime
	err := q.db.QueryRowContext(ctx, `
		SELECT `+apiKeyColumns+`
		FROM api_keys
		WHERE key_prefix = $1
	`, prefix).Scan(
		&k.ID, &k.Username, &k.Name, &k.KeyPrefix, &k.KeyHash,
		&k.CreatedAt, &lastUsed, &expires, &revoked,
	)
	if err != nil {
		return nil, err
	}
	if lastUsed.Valid {
		k.LastUsedAt = &lastUsed.Time
	}
	if expires.Valid {
		k.ExpiresAt = &expires.Time
	}
	if revoked.Valid {
		k.RevokedAt = &revoked.Time
	}
	return &k, nil
}

// GetAPIKeyScopes loads scopes by api_key_id. Bypasses RLS by design — used
// by the middleware verify path which authenticates by the secret half of the
// key, not by an active user session.
func (q *Queries) GetAPIKeyScopes(ctx context.Context, apiKeyID uuid.UUID) ([]models.APIKeyScope, error) {
	rows, err := q.db.QueryContext(ctx, `
		SELECT id, api_key_id, operation, path_prefix
		FROM api_key_scopes
		WHERE api_key_id = $1
	`, apiKeyID)
	if err != nil {
		return nil, fmt.Errorf("GetAPIKeyScopes: %w", err)
	}
	defer rows.Close()
	var out []models.APIKeyScope
	for rows.Next() {
		var s models.APIKeyScope
		if err := rows.Scan(&s.ID, &s.APIKeyID, &s.Operation, &s.PathPrefix); err != nil {
			return nil, fmt.Errorf("GetAPIKeyScopes scan: %w", err)
		}
		out = append(out, s)
	}
	return out, rows.Err()
}

// TouchAPIKeyLastUsed updates last_used_at. Called fire-and-forget from the
// middleware on every successful verify. Bypasses RLS for the same reason as
// GetAPIKeyByPrefix.
func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, apiKeyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, `UPDATE api_keys SET last_used_at = NOW() WHERE id = $1`, apiKeyID)
	if err != nil {
		return fmt.Errorf("TouchAPIKeyLastUsed: %w", err)
	}
	return nil
}

// RevokeAPIKey marks a key revoked. Must run inside a ForUser tx for RLS.
// Idempotent — revoking an already-revoked key is a no-op.
func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, `
		UPDATE api_keys
		SET revoked_at = COALESCE(revoked_at, NOW())
		WHERE id = $1
	`, id)
	if err != nil {
		return fmt.Errorf("RevokeAPIKey: %w", err)
	}
	return nil
}

// RevokeAllAPIKeysForUser bulk-revokes every active key for a user. Called
// from the payment refund / dispute handler. Bypasses RLS (privileged path).
func (q *Queries) RevokeAllAPIKeysForUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, `
		UPDATE api_keys
		SET revoked_at = NOW()
		WHERE username = $1 AND revoked_at IS NULL
	`, username)
	if err != nil {
		return fmt.Errorf("RevokeAllAPIKeysForUser %q: %w", username, err)
	}
	return nil
}

