package db

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"apollo-sfs.com/api/models"
)

const snapshotColumns = `
	id, cpu_percent, memory_used_bytes, memory_total_bytes,
	network_bytes_sent, network_bytes_recv,
	storage_total_used_bytes, storage_total_quota_bytes,
	disk_total_bytes, disk_free_bytes,
	active_user_count, total_user_count, sampled_at,
	cpu_temp_celsius, drive_temp_celsius,
	server_isp_ping_ms, server_isp_packet_loss_percent`

func scanSnapshot(rows *sql.Rows) (*models.ServerMetricSnapshot, error) {
	var s models.ServerMetricSnapshot
	err := rows.Scan(
		&s.ID, &s.CPUPercent, &s.MemoryUsedBytes, &s.MemoryTotalBytes,
		&s.NetworkBytesSent, &s.NetworkBytesRecv,
		&s.StorageTotalUsedBytes, &s.StorageTotalQuotaBytes,
		&s.DiskTotalBytes, &s.DiskFreeBytes,
		&s.ActiveUserCount, &s.TotalUserCount, &s.SampledAt,
		&s.CPUTempCelsius, &s.DriveTempCelsius,
		&s.ServerISPPingMs, &s.ServerISPPacketLossPercent,
	)
	return &s, err
}

// InsertSnapshot persists a new server metrics snapshot and populates s.ID
// with the UUID generated by the database.
func (q *Queries) InsertSnapshot(ctx context.Context, s *models.ServerMetricSnapshot) error {
	err := q.db.QueryRowContext(ctx, `
		INSERT INTO server_metrics_snapshots (
			id, cpu_percent, memory_used_bytes, memory_total_bytes,
			network_bytes_sent, network_bytes_recv,
			storage_total_used_bytes, storage_total_quota_bytes,
			disk_total_bytes, disk_free_bytes,
			active_user_count, total_user_count, sampled_at,
			cpu_temp_celsius, drive_temp_celsius,
			server_isp_ping_ms, server_isp_packet_loss_percent
		) VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
		RETURNING id
	`,
		s.CPUPercent, s.MemoryUsedBytes, s.MemoryTotalBytes,
		s.NetworkBytesSent, s.NetworkBytesRecv,
		s.StorageTotalUsedBytes, s.StorageTotalQuotaBytes,
		s.DiskTotalBytes, s.DiskFreeBytes,
		s.ActiveUserCount, s.TotalUserCount, s.SampledAt,
		s.CPUTempCelsius, s.DriveTempCelsius,
		s.ServerISPPingMs, s.ServerISPPacketLossPercent,
	).Scan(&s.ID)
	if err != nil {
		return fmt.Errorf("InsertSnapshot: %w", err)
	}
	return nil
}

// GetLatestSnapshot returns the most recently sampled row.
// Returns sql.ErrNoRows if the table is empty.
func (q *Queries) GetLatestSnapshot(ctx context.Context) (*models.ServerMetricSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, `
		SELECT`+snapshotColumns+`
		FROM server_metrics_snapshots
		ORDER BY sampled_at DESC
		LIMIT 1
	`)
	if err != nil {
		return nil, fmt.Errorf("GetLatestSnapshot: %w", err)
	}
	defer rows.Close()

	if !rows.Next() {
		return nil, fmt.Errorf("GetLatestSnapshot: %w", sql.ErrNoRows)
	}
	s, err := scanSnapshot(rows)
	if err != nil {
		return nil, fmt.Errorf("GetLatestSnapshot scan: %w", err)
	}
	return s, rows.Err()
}

// ListSnapshots returns a page of snapshots ordered by sampled_at descending.
// Uses time-cursor pagination: the cursor encodes the sampled_at of the last
// returned row. Pass an empty PageInput to start from the most recent snapshot.
func (q *Queries) ListSnapshots(ctx context.Context, in PageInput) (*PageResult[models.ServerMetricSnapshot], error) {
	limit := clampLimit(in.Limit)
	before, err := decodeTimeCursor(in.Cursor)
	if err != nil {
		return nil, fmt.Errorf("ListSnapshots: %w", err)
	}

	var sqlRows *sql.Rows
	if before.IsZero() {
		sqlRows, err = q.db.QueryContext(ctx, `
			SELECT`+snapshotColumns+`
			FROM server_metrics_snapshots
			ORDER BY sampled_at DESC
			LIMIT $1
		`, limit)
	} else {
		sqlRows, err = q.db.QueryContext(ctx, `
			SELECT`+snapshotColumns+`
			FROM server_metrics_snapshots
			WHERE sampled_at < $1
			ORDER BY sampled_at DESC
			LIMIT $2
		`, before, limit)
	}
	if err != nil {
		return nil, fmt.Errorf("ListSnapshots: %w", err)
	}
	defer sqlRows.Close()

	var snaps []models.ServerMetricSnapshot
	for sqlRows.Next() {
		s, err := scanSnapshot(sqlRows)
		if err != nil {
			return nil, fmt.Errorf("ListSnapshots scan: %w", err)
		}
		snaps = append(snaps, *s)
	}
	if err := sqlRows.Err(); err != nil {
		return nil, fmt.Errorf("ListSnapshots: %w", err)
	}

	var nextToken string
	if len(snaps) == limit {
		nextToken = encodeTimeCursor(snaps[len(snaps)-1].SampledAt)
	}
	return &PageResult[models.ServerMetricSnapshot]{
		Items:     snaps,
		NextToken: nextToken,
	}, nil
}

// ListSnapshotsByDate returns a page of snapshots for a specific calendar day.
// date must be in mm-dd-yyyy format (e.g. "04-15-2026").
// Secondary index: server_metrics_snapshots.sampled_at should be indexed in the DB migration.
func (q *Queries) ListSnapshotsByDate(ctx context.Context, date string, in PageInput) (*PageResult[models.ServerMetricSnapshot], error) {
	day, err := time.Parse("01-02-2006", date)
	if err != nil {
		return nil, fmt.Errorf("ListSnapshotsByDate: invalid date %q, expected mm-dd-yyyy: %w", date, err)
	}

	start := time.Date(day.Year(), day.Month(), day.Day(), 0, 0, 0, 0, time.UTC)
	end := start.Add(24 * time.Hour)

	limit := clampLimit(in.Limit)
	offset, err := decodeOffsetCursor(in.Cursor)
	if err != nil {
		return nil, fmt.Errorf("ListSnapshotsByDate: %w", err)
	}

	rows, err := q.db.QueryContext(ctx, `
		SELECT`+snapshotColumns+`
		FROM server_metrics_snapshots
		WHERE sampled_at >= $1 AND sampled_at < $2
		ORDER BY sampled_at ASC
		LIMIT $3 OFFSET $4
	`, start, end, limit, offset)
	if err != nil {
		return nil, fmt.Errorf("ListSnapshotsByDate: %w", err)
	}
	defer rows.Close()

	var snaps []models.ServerMetricSnapshot
	for rows.Next() {
		s, err := scanSnapshot(rows)
		if err != nil {
			return nil, fmt.Errorf("ListSnapshotsByDate scan: %w", err)
		}
		snaps = append(snaps, *s)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListSnapshotsByDate: %w", err)
	}
	return &PageResult[models.ServerMetricSnapshot]{
		Items:     snaps,
		NextToken: offsetNextToken(len(snaps), limit, offset),
	}, nil
}

// ListSnapshotsByHours returns at most maxPoints evenly-distributed snapshots
// from the past hours hours, ordered oldest-first. Uses NTILE downsampling so
// the returned points cover the full interval regardless of data density.
func (q *Queries) ListSnapshotsByHours(ctx context.Context, hours, maxPoints int) ([]models.ServerMetricSnapshot, error) {
	cutoff := time.Now().UTC().Add(-time.Duration(hours) * time.Hour)

	rows, err := q.db.QueryContext(ctx, `
		SELECT DISTINCT ON (bucket)
			id, cpu_percent, memory_used_bytes, memory_total_bytes,
			network_bytes_sent, network_bytes_recv,
			storage_total_used_bytes, storage_total_quota_bytes,
			disk_total_bytes, disk_free_bytes,
			active_user_count, total_user_count, sampled_at,
			cpu_temp_celsius, drive_temp_celsius,
			server_isp_ping_ms, server_isp_packet_loss_percent
		FROM (
			SELECT
				id, cpu_percent, memory_used_bytes, memory_total_bytes,
				network_bytes_sent, network_bytes_recv,
				storage_total_used_bytes, storage_total_quota_bytes,
				disk_total_bytes, disk_free_bytes,
				active_user_count, total_user_count, sampled_at,
				cpu_temp_celsius, drive_temp_celsius,
				server_isp_ping_ms, server_isp_packet_loss_percent,
				NTILE($1) OVER (ORDER BY sampled_at ASC) AS bucket
			FROM server_metrics_snapshots
			WHERE sampled_at >= $2
		) sub
		ORDER BY bucket, sampled_at ASC
	`, maxPoints, cutoff)
	if err != nil {
		return nil, fmt.Errorf("ListSnapshotsByHours: %w", err)
	}
	defer rows.Close()

	var snaps []models.ServerMetricSnapshot
	for rows.Next() {
		s, err := scanSnapshot(rows)
		if err != nil {
			return nil, fmt.Errorf("ListSnapshotsByHours scan: %w", err)
		}
		snaps = append(snaps, *s)
	}
	return snaps, rows.Err()
}

// PruneOldSnapshots deletes all snapshots sampled before the given time.
// Called daily by a background goroutine to enforce the 7-day retention policy.
func (q *Queries) PruneOldSnapshots(ctx context.Context, before time.Time) error {
	_, err := q.db.ExecContext(ctx,
		`DELETE FROM server_metrics_snapshots WHERE sampled_at < $1`,
		before,
	)
	if err != nil {
		return fmt.Errorf("PruneOldSnapshots: %w", err)
	}
	return nil
}
