#!/usr/bin/env bash
# Fetches current Cloudflare IP ranges from the public API and regenerates
# /etc/nginx/conf.d/cloudflare-real-ip.conf. Reloads nginx only when the
# ranges have actually changed. Run by the cf-ip-refresh systemd timer.
set -euo pipefail

API_URL="https://api.cloudflare.com/client/v4/ips"
NGINX_CONF="/etc/nginx/conf.d/cloudflare-real-ip.conf"

log() { echo "$(date -u +%FT%TZ) cf-ip-refresh: $*"; }

# Fetch with a strict timeout so a Cloudflare outage never blocks nginx reload.
response=$(curl -sf --max-time 30 "$API_URL") || {
    log "ERROR: Cloudflare API request failed — keeping existing config"
    exit 1
}

# Parse and generate the nginx include using only python3 (available on any
# modern Debian/Ubuntu system; no jq required).
new_conf=$(python3 - "$response" <<'EOF'
import sys, json
from datetime import datetime, timezone

data = json.loads(sys.argv[1])
if not data.get("success"):
    print("ERROR: API returned success=false", file=sys.stderr)
    sys.exit(1)

result   = data["result"]
ipv4     = result.get("ipv4_cidrs", [])
ipv6     = result.get("ipv6_cidrs", [])
ts       = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

lines = [
    "# Auto-generated by cf-ip-refresh — DO NOT EDIT MANUALLY.",
    f"# Last updated: {ts}",
    f"# Source: https://api.cloudflare.com/client/v4/ips",
    "",
    "real_ip_header    CF-Connecting-IP;",
    "real_ip_recursive on;",
    "",
    "# IPv4",
]
lines += [f"set_real_ip_from {c};" for c in sorted(ipv4)]
lines += ["", "# IPv6"]
lines += [f"set_real_ip_from {c};" for c in sorted(ipv6)]

print("\n".join(lines))
EOF
)

# Write to a temp file, diff, swap — never leave nginx with a broken config.
tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT
echo "$new_conf" > "$tmpfile"

if [ -f "$NGINX_CONF" ] && diff -q "$tmpfile" "$NGINX_CONF" > /dev/null 2>&1; then
    log "no changes — nginx not reloaded"
    exit 0
fi

cp "$tmpfile" "$NGINX_CONF"

if nginx -t 2>/dev/null; then
    nginx -s reload
    log "updated Cloudflare IP ranges and reloaded nginx"
else
    log "ERROR: nginx config test failed after update — investigate $NGINX_CONF"
    exit 1
fi
