-- File metadata. The encrypted blob lives in MinIO at minio_object_key.
-- nonce is the AES-GCM nonce used to encrypt the blob.
-- user_id stores the Keycloak subject UUID (same type note as folders).
-- folder_id is nullable: NULL means the file lives at the root level.
-- Deleting a folder cascades to its files here; the caller must also delete
-- the corresponding MinIO object before or after removing the metadata row.

CREATE TABLE files (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          UUID        NOT NULL,
    folder_id        UUID        REFERENCES folders (id) ON DELETE CASCADE,
    drive_id         UUID        REFERENCES drives (id),
    name             TEXT        NOT NULL,
    mime_type        TEXT        NOT NULL DEFAULT 'application/octet-stream',
    size_bytes       BIGINT      NOT NULL DEFAULT 0,
    minio_object_key TEXT        NOT NULL UNIQUE,
    nonce            BYTEA       NOT NULL,
    -- taken_at is the capture date extracted from media metadata (EXIF for
    -- images, container metadata for videos). NULL when unavailable; callers
    -- fall back to created_at for sorting.
    taken_at         TIMESTAMPTZ,
    -- hidden files are excluded from collection listings unless explicitly
    -- requested via a "show hidden" toggle or the dedicated hidden view.
    hidden           BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX files_user_id_idx   ON files (user_id);
CREATE INDEX files_folder_id_idx ON files (folder_id);
CREATE INDEX files_taken_at_idx  ON files (folder_id, taken_at);

-- Unique filename per folder for non-root files.
CREATE UNIQUE INDEX files_unique_name_per_folder
    ON files (user_id, folder_id, name)
    WHERE folder_id IS NOT NULL;

-- Unique filename at root level (folder_id IS NULL).
CREATE UNIQUE INDEX files_unique_name_at_root
    ON files (user_id, name)
    WHERE folder_id IS NULL;

-- Row-level security: queries must run inside a transaction that sets
-- app.current_user_id to the requesting user's UUID via db.Queries.ForUser().
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
ALTER TABLE files FORCE  ROW LEVEL SECURITY;

CREATE POLICY files_owned_by_current_user ON files
    USING      (user_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid)
    WITH CHECK (user_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid);

-- ── Video variants ────────────────────────────────────────────────────────────
-- Low-resolution variants generated by background FFmpeg transcoding.
-- status: 'pending' (queued/running), 'ready' (streamable), 'failed' (transcode error).
-- Rows are cascade-deleted when the parent files row is removed.

CREATE TABLE video_variants (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    file_id          UUID        NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    quality          TEXT        NOT NULL,
    minio_object_key TEXT        NOT NULL UNIQUE,
    size_bytes       BIGINT      NOT NULL DEFAULT 0,
    status           TEXT        NOT NULL DEFAULT 'pending',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (file_id, quality)
);

CREATE INDEX video_variants_file_id_idx ON video_variants (file_id);
