/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthClientIndexRouteImport } from './routes/_auth.client/index'
import { Route as AuthClientProfileRouteImport } from './routes/_auth.client/profile'
import { Route as AuthClientFavoritesRouteImport } from './routes/_auth.client/favorites'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth.admin/users'
import { Route as AuthAdminMetricsRouteImport } from './routes/_auth.admin/metrics'
import { Route as AuthAdminInvitationsRouteImport } from './routes/_auth.admin/invitations'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthClientIndexRoute = AuthClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientProfileRoute = AuthClientProfileRouteImport.update({
  id: '/client/profile',
  path: '/client/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientFavoritesRoute = AuthClientFavoritesRouteImport.update({
  id: '/client/favorites',
  path: '/client/favorites',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminMetricsRoute = AuthAdminMetricsRouteImport.update({
  id: '/admin/metrics',
  path: '/admin/metrics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminInvitationsRoute = AuthAdminInvitationsRouteImport.update({
  id: '/admin/invitations',
  path: '/admin/invitations',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/invitations': typeof AuthAdminInvitationsRoute
  '/admin/metrics': typeof AuthAdminMetricsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/client/favorites': typeof AuthClientFavoritesRoute
  '/client/profile': typeof AuthClientProfileRoute
  '/client/': typeof AuthClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/invitations': typeof AuthAdminInvitationsRoute
  '/admin/metrics': typeof AuthAdminMetricsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/client/favorites': typeof AuthClientFavoritesRoute
  '/client/profile': typeof AuthClientProfileRoute
  '/client': typeof AuthClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/admin/invitations': typeof AuthAdminInvitationsRoute
  '/_auth/admin/metrics': typeof AuthAdminMetricsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/client/favorites': typeof AuthClientFavoritesRoute
  '/_auth/client/profile': typeof AuthClientProfileRoute
  '/_auth/client/': typeof AuthClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/invitations'
    | '/admin/metrics'
    | '/admin/users'
    | '/client/favorites'
    | '/client/profile'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/invitations'
    | '/admin/metrics'
    | '/admin/users'
    | '/client/favorites'
    | '/client/profile'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/admin/invitations'
    | '/_auth/admin/metrics'
    | '/_auth/admin/users'
    | '/_auth/client/favorites'
    | '/_auth/client/profile'
    | '/_auth/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/client/': {
      id: '/_auth/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthClientIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/client/profile': {
      id: '/_auth/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof AuthClientProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/client/favorites': {
      id: '/_auth/client/favorites'
      path: '/client/favorites'
      fullPath: '/client/favorites'
      preLoaderRoute: typeof AuthClientFavoritesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/metrics': {
      id: '/_auth/admin/metrics'
      path: '/admin/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AuthAdminMetricsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/invitations': {
      id: '/_auth/admin/invitations'
      path: '/admin/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AuthAdminInvitationsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminInvitationsRoute: typeof AuthAdminInvitationsRoute
  AuthAdminMetricsRoute: typeof AuthAdminMetricsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthClientFavoritesRoute: typeof AuthClientFavoritesRoute
  AuthClientProfileRoute: typeof AuthClientProfileRoute
  AuthClientIndexRoute: typeof AuthClientIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminInvitationsRoute: AuthAdminInvitationsRoute,
  AuthAdminMetricsRoute: AuthAdminMetricsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthClientFavoritesRoute: AuthClientFavoritesRoute,
  AuthClientProfileRoute: AuthClientProfileRoute,
  AuthClientIndexRoute: AuthClientIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
